name: SemVer Tag Created CI
run-name: 'Deploy ${{ github.ref_name }} to development by ${{ github.actor }}'

on:
  push:
    tags: ["v*.*.*"]

jobs:
  deploy-dags-dev:
    strategy:
      matrix:
        domain: [ "uk", "india" ]

    uses: ./.github/workflows/deploy.yml
    with:
      deploy_target: "development"
      domain: ${{ matrix.domain }}
      tag: ${{ github.ref_name }}
    secrets: inherit

